apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-souza  
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "512Mi"
          cpu: "300m"
        limits:
          memory: "512Mi"
          cpu: "300m"