apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-souza
  labels:
    app: nginx
    type: pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "512Mi"
          cpu: "300m"
        limits:
          memory: "512Mi"
          cpu: "300m"
      # readinessProbe:
      #   tcpSocket:
      #     port: 80
      #   initialDelaySeconds: 5
      #   periodSeconds: 10
      # livenessProbe:
      #   tcpSocket:
      #     port: 80
      #   initialDelaySeconds: 15
      #   periodSeconds: 20