apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: test-souza
  labels:
    app: nginx-app
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
